spring:
  application:
    name: myapp
  profiles:
    default: local

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/myapp
    username: app
    password: app
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

server:
  port: 8080
